import { Avatar } from './types';

export const avatars: Avatar[] = [
  {
    id: 'man',
    name: 'Classic Man',
    image: '/avatars/man.png',
    faceArea: {
      x: 125,
      y: 110,
      width: 150,
      height: 180,
      rotate: 0,
    },
  },
  {
    id: 'woman',
    name: 'Elegant Woman',
    image: '/avatars/woman.png',
    faceArea: {
      x: 130,
      y: 115,
      width: 140,
      height: 170,
      rotate: 0,
    },
  },
  {
    id: 'denim-blue-peack',
    name: 'Blue Peack Denim Dress',
    image: '/images/HIGHLITS/Denim/Blue Peack Denim Short Dress.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'denim-patchwork-pants',
    name: 'Denim Patchwork Pants Set',
    image: '/images/HIGHLITS/Denim/Denim patchwork Set Top and Pants with Peaco Printer.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'denim-patchwork-skirt',
    name: 'Denim Patchwork Skirt Set',
    image: '/images/HIGHLITS/Denim/Denim patchwork Set Top and Skirt with Peacok Printer.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'leather-blouson',
    name: 'Leather Blouson Floral',
    image: '/images/HIGHLITS/Denim/LEATHER BLOUSON WITH FLORAL PATCHES.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'leather-dress-gold',
    name: 'Leather Dress Gold Peacock',
    image: '/images/HIGHLITS/Denim/LEATHER DRESS WITH GOLD PEACOCK DETAILS.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'long-dress-denim',
    name: 'Long Dress Denim Chains',
    image: '/images/HIGHLITS/Denim/Long Dress Denim Iron Chains.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'peacock-monogram-coat',
    name: 'Peacock Monogram Coat',
    image: '/images/HIGHLITS/Denim/PEACOCK MONOGRAM EMBOSSED LEATHER TAILORED COAT.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'peacock-print-denim-dress',
    name: 'Peacock Print Denim Dress',
    image: '/images/HIGHLITS/Denim/Peacock Print Leather Denim Short Dress.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'peacos-denim-pants',
    name: 'Peacos Denim Loose Pants',
    image: '/images/HIGHLITS/Denim/Peacos Denim Light Blue And Dark Loose Pants.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'vintage-peacock-jacket',
    name: 'Vintage Peacock Biker Jacket',
    image: '/images/HIGHLITS/Denim/VINTAGE PEACOCK LEATHER BIKER JACKET.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-draped-jersey',
    name: 'Draped Jersey Knotted Dress',
    image: '/images/HIGHLITS/MESH/DRAPED JERSEY KNOTTED BLACK DRESS WITH PEACOCK PRINT.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-golden-majesty',
    name: 'Golden Peacock Majesty Gown',
    image: '/images/HIGHLITS/MESH/GOLDEN PEACOCK MAJESTY LONG BLACK DRESS.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-knitted-shell',
    name: 'Modern Heritage Knitted Set',
    image: '/images/HIGHLITS/MESH/Modern Heritage Knitted black shell Set.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-flock-mini',
    name: 'Peacock Mesh Flock Mini Dress',
    image: '/images/HIGHLITS/MESH/PEACOCK MESH FLOCK LS MINI CREWNECK DRESS.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-flock-straps',
    name: 'Peacock Mesh Flock Straps Top',
    image: '/images/HIGHLITS/MESH/PEACOCK MESH FLOCK STRAPS TOP.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-flock-coverups',
    name: 'Peacock Mesh Flock Cover-ups',
    image: '/images/HIGHLITS/MESH/PEACOCK MESHFLOCK COVER-UPS.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-monogram-red-top',
    name: 'Peacock Monogram Red Cropped Top',
    image: '/images/HIGHLITS/MESH/PEACOCK MONOGRAM MESH FLOCK LS RED CROPPED TOP.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-gilded-gala',
    name: 'The Gilded Peacock Gala Gown',
    image: '/images/HIGHLITS/MESH/The Gilded Peacock Gala Gown.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-obsidian-crown',
    name: 'The Obsidian Crown Gown',
    image: '/images/HIGHLITS/MESH/The Obsidian Crown Gown long black dress.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-velvet-muse',
    name: 'Zafira Velvet Muse Dress',
    image: '/images/HIGHLITS/MESH/The Zafira black in dark red Velvet Muse with gold peacock print.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-mini-monogram-set',
    name: 'Zafira Mini Monogram Set',
    image: '/images/HIGHLITS/MESH/The black Zafira Set with mini peacock monogram.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-blue-peack-denim',
    name: 'Blue Peack Denim Dress (Mesh)',
    image: '/images/HIGHLITS/MESH/Blue Peack Denim Short Dress.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-leather-dress-gold',
    name: 'Leather Dress Gold Peacock (Mesh)',
    image: '/images/HIGHLITS/MESH/LEATHER DRESS WITH GOLD PEACOCK DETAILS.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-long-dress-denim',
    name: 'Long Dress Denim Iron Chains (Mesh)',
    image: '/images/HIGHLITS/MESH/Long Dress Denim Iron Chains.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
  {
    id: 'mesh-peacock-print-denim',
    name: 'Peacock Print Leather Denim Dress (Mesh)',
    image: '/images/HIGHLITS/MESH/Peacock Print Leather Denim Short Dress.jpg',
    faceArea: { x: 130, y: 120, width: 140, height: 170, rotate: 0 },
  },
];

export const DEFAULT_AVATAR = avatars[0];
